targets:
  $default:
    builders:
      json_serializable:
        options:
          # 使用显式命名，避免字段重命名问题
          explicit_to_json: true
          # 使用字段重命名，支持下划线转小驼峰
          field_rename: snake
          # 创建工厂构造函数
          create_factory: true
          # 包含空值
          include_if_null: false
      freezed:
        options:
          # 生成toString方法
          to_string: true
          # 生成不可变副本方法
          copy_with: true 